### ISSUE TITLE
示例自定义组件依旧是vue2呢

### ISSUE THREAD

**Issue by Zhaobudaoyuema** [aisuda/vue3-amis-custom-widget#1]
示例代码描述的很清晰，但是示例组件开发还是vue2.可否我来加vue3的示例组件

**Comment by wibetter** [comment]
@Zhaobudaoyuema  是说这个模板没有采用vue3最新的语法实现吧，如果想看vue3的组合式写法，可以看这里：https://github.com/aisuda/amis-widget/tree/feat-vue3。
我们也欢迎你自己实现一个vue3写法的自定义组件模板然后提pr。
